name: Build Archiso Weekly

on:
  schedule:
    - cron: '0 0 * * 0'  # Every Sunday at midnight UTC
  workflow_dispatch:  # Manual trigger

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      options: --privileged
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y.%m.%d')" >> $GITHUB_OUTPUT

      - name: Setup pacman cache
        uses: actions/cache@v4
        with:
          path: /var/cache/pacman/pkg
          key: archiso-pacman-${{ steps.date.outputs.date }}
          restore-keys: |
            archiso-pacman-

      - name: Configure pacman for optimal performance
        run: |
          sed -i 's/#ParallelDownloads = 5/ParallelDownloads = 5/' /etc/pacman.conf
          sed -i 's/#Color/Color/' /etc/pacman.conf

      - name: Initialize Arch keyring and update system
        run: |
          pacman-key --init
          pacman-key --populate archlinux
          pacman -Sy --noconfirm archlinux-keyring
          pacman -Syu --noconfirm

      - name: Install archiso and dependencies
        run: |
          pacman -S --noconfirm archiso git

      - name: Setup archiso profile cache
        id: profile-cache
        uses: actions/cache@v4
        with:
          path: /tmp/archiso-profile
          key: archiso-profile-v1
          restore-keys: |
            archiso-profile-

      - name: Copy archiso releng profile
        run: |
          if [ -d /tmp/archiso-profile ]; then
            echo "Using cached profile"
            cp -r /tmp/archiso-profile /tmp/archiso
          else
            echo "Creating fresh profile"
            cp -r /usr/share/archiso/configs/releng /tmp/archiso
            cp -r /tmp/archiso /tmp/archiso-profile
          fi

      - name: Build ISO
        run: |
          cd /tmp
          mkarchiso -v -w /tmp/archiso-work -o /tmp/out /tmp/archiso

      - name: Generate checksums
        run: |
          cd /tmp/out
          ISO_FILE=$(ls archlinux-*.iso)
          sha256sum "$ISO_FILE" > "$ISO_FILE.sha256"
          sha512sum "$ISO_FILE" > "$ISO_FILE.sha512"
          echo "ISO_NAME=$ISO_FILE" >> $GITHUB_ENV

      - name: Upload ISO artifact
        uses: actions/upload-artifact@v4
        with:
          name: archlinux-${{ steps.date.outputs.date }}-x86_64
          path: |
            /tmp/out/*.iso
            /tmp/out/*.sha256
            /tmp/out/*.sha512
          retention-days: 90
          compression-level: 9

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.date.outputs.date }}
          name: Arch Linux ISO ${{ steps.date.outputs.date }}
          body: |
            ## Arch Linux Live ISO - Weekly Build
            
            **Build Date:** ${{ steps.date.outputs.date }}
            **Profile:** releng (official)
            **Architecture:** x86_64
            
            ### Included Packages
            This ISO includes the official Arch Linux releng profile with ~130 packages:
            - Base system (base, linux, linux-firmware)
            - Installation tools (archinstall, gpart, gparted)
            - Networking (networkmanager, openssh, wireless_tools, wpa_supplicant)
            - Filesystems (btrfs-progs, dosfstools, e2fsprogs, f2fs-tools, ntfs-3g, xfsprogs)
            - System utilities (git, vim, nano, tmux, screen, htop)
            - Hardware support (amd-ucode, intel-ucode, nvme-cli, smartmontools)
            - Web browsers (elinks, lynx)
            - And more...
            
            ### Verification
            ```bash
            # Verify SHA256
            sha256sum -c archlinux-${{ steps.date.outputs.date }}-x86_64.iso.sha256
            
            # Verify SHA512
            sha512sum -c archlinux-${{ steps.date.outputs.date }}-x86_64.iso.sha512
            ```
            
            ### Usage
            ```bash
            # Write to USB (Linux)
            sudo dd if=archlinux-${{ steps.date.outputs.date }}-x86_64.iso of=/dev/sdX bs=4M status=progress && sync
            
            # Or use balenaEtcher, Rufus (Windows), or similar tools
            ```
          files: |
            /tmp/out/*.iso
            /tmp/out/*.sha256
            /tmp/out/*.sha512
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build summary
        run: |
          cd /tmp/out
          ISO_FILE=$(ls archlinux-*.iso)
          ISO_SIZE=$(du -h "$ISO_FILE" | cut -f1)
          echo "### Build Complete! 🎉" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**ISO:** $ISO_FILE" >> $GITHUB_STEP_SUMMARY
          echo "**Size:** $ISO_SIZE" >> $GITHUB_STEP_SUMMARY
          echo "**Date:** ${{ steps.date.outputs.date }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "#### Checksums" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          cat "$ISO_FILE.sha256" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
